unique_name: Product
object_type: dimension
label: Product
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    levels:
      - unique_name: productname
      - unique_name: productcategory
level_attributes:
  - unique_name: productname
    label: product name
    contains_unique_names: false
    dataset: products
    is_unique_key: false
    key_columns:
      - productid
    name_column: productname
  - unique_name: productcategory
    label: product category
    contains_unique_names: false
    dataset: products
    is_unique_key: false
    key_columns:
      - productcategory
    name_column: productcategory
type: standard
